POST http://localhost:3030/cards
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJpYXQiOjE3MTc3Njc0MjAsImV4cCI6MTcxNzg1MzgyMCwiYXVkIjoiaHR0cHM6Ly9leGFtcGxlLmNvbSIsInN1YiI6IjY2NjBiMTAxMmVlM2E4YWQ3MDAzYWNhOCIsImp0aSI6ImJjMWUxOTcyLWQ3Y2ItNDliOS1iMmQwLTdkZWEzMWUxZjgxZSJ9.nmZIuQjUrcWSp2nlkybnPs-4ygqNa0N65Sci8IKHowY

{
  "text": "Card text 5",
  "listId": "66634c7639c5a3fc45006086"
}
